USE VCD_MANAGER;

SHOW TABLES;

SHOW TRIGGERS;

SELECT * FROM VCD;
SELECT * FROM USER;
SELECT * FROM SUPPLIER;
SELECT * FROM STOCK;
SELECT * FROM VCD_SUPPLY;
SELECT * FROM VCD_RENT;
SELECT * FROM VCD_RETURN;
SELECT * FROM VCD_SALE;
-- DELETE FROM USER WHERE id < 100;
