USE VCD_MANAGER;

-- 触发器：借出 VCD 更新库存现货项
DROP TRIGGER IF EXISTS VCD_MANAGER.UPDATE_AVAILABLE_IN_STOCK_WHEN_RENT;

-- 触发器：归还 VCD 更新库存现货项
DROP TRIGGER IF EXISTS VCD_MANAGER.UPDATE_AVAILABLE_IN_STOCK_WHEN_RETURN;

-- 触发器：售出修改库存现货项/库存项
DROP TRIGGER IF EXISTS VCD_MANAGER.UPDATE_AVAILABLE_STOCKED_IN_STOCK_WHEN_SALE;

-- 触发器：入库修改库存现货项/库存项
DROP TRIGGER IF EXISTS VCD_MANAGER.UPDATE_AVAILABLE_STOCKED_IN_STOCK_WHEN_SUPPLY;

SHOW TRIGGERS;
